### ISSUE TITLE
how do we show type for namespace?

### ISSUE THREAD

**Issue by pur3miish** [jaydenseric/jsdoc-md#10]
I am trying to build the equivalent of a ts interface.

So far I have...

```js
/**
 * The account name and ABI.
 * @kind namespace
 * @name AccountAndAbi
 */

/**
 * Account name.
 * @kind constant
 * @name AccountAndAbi.account_name
 * @type {string}
 */

/**
 * ABI Uint8Array binary representation
 * @kind constant
 * @name AccountAndAbi.abi
 * @type {Uint8Array}
 */
```

which produces this...

<img width="459" alt="screenshot 2018-11-17 at 21 21 43" src="https://user-images.githubusercontent.com/16223777/48660535-d3988f80-eaae-11e8-9fc9-19286cd6b949.png">

I would like to know is their anyway to get the types included in the generated MD, or is there another way you suggest to writing a namespace?

Thanks.

**Comment by jaydenseric** [comment]
I think you are describing the use case for a `typedef`?

Example:

- Source: https://github.com/jaydenseric/graphql-upload/blob/e0ff3d09018ef9d725850643c278a51a9ae03765/src/processRequest.mjs#L7
- MD: https://github.com/jaydenseric/graphql-upload#type-uploadoptions

Keep in mind also, that the namepath `.` means static member. Sometimes when name spacing for JSDoc `~` is more appropriate; it means inner member.

**Comment by pur3miish** [comment]
Awesome, you are correct that I needed a typedef.

It works perfectly now.

<img width="320" alt="screenshot 2018-11-18 at 12 16 26" src="https://user-images.githubusercontent.com/16223777/48667860-d4233b80-eb2b-11e8-8c5b-8a9ef806007c.png">


Thanks for your help.
