### ISSUE TITLE
Sort members in the documentation outline

### ISSUE THREAD

**Issue by jaydenseric** [jaydenseric/jsdoc-md#8]
At the moment, the order of documented members is largely determined by the order the JSDoc is scraped from the source code. Sorting members so that similar kinds are grouped (at each level), with typedefs grouped last, with alphabetical sort on pathnames within groups, would make the docs more coherent. It would also make the order deterministic, so that refactoring the order of functions etc. in source code will not result in large readme diffs.

The best place for sorting is likely in [`outlineMembers`](https://github.com/jaydenseric/jsdoc-md/blob/v1.3.0/lib/outlineMembers.js#L17).

**Comment by jaydenseric** [comment]
@pur3miish my first attempt:

```diff
 const outlineMembers = members => {
    // Prevent modification of the input array.
-   const outline = members.slice()
+   const outline = members.sort((a, b) => {
+     if (
+       // Group static members fourth last.
+       (a.membership === '.' && b.membership !== '.') ||
+       // Group instance members third last.
+       (a.membership === '#' && b.membership !== '#') ||
+       // Group inner members second last.
+       (a.membership === '~' && b.membership !== '~') ||
+       // Group typedefs last.
+       (a.kind === 'typedef' && b.kind !== 'typedef')
+     )
+       return 1
+
+     // Case-insensitive alphabetic order.
+     const namepathA = a.namepath.toLowerCase()
+     const namepathB = b.namepath.toLowerCase()
+     if (namepathA < namepathB) return -1
+     if (namepathA > namepathB) return 1
+     return 0
+   })
```

**Comment by pur3miish** [comment]
lets just use bubble sort 🤣
