### ISSUE TITLE
We should support Uint8Array?

### ISSUE THREAD

**Issue by pur3miish** [jaydenseric/jsdoc-md#9]
What about adding support for Type [Uint8Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array) currently it is not linking like our other types.

<img width="286" alt="screenshot 2018-11-17 at 13 42 49" src="https://user-images.githubusercontent.com/16223777/48656289-bcd24880-ea6e-11e8-9957-d0c33021393c.png">

I can do a PR soonish?

**Comment by jaydenseric** [comment]
Sure, PR welcome :)

**Comment by pur3miish** [comment]
PR https://github.com/jaydenseric/jsdoc-md/pull/11

**Comment by jaydenseric** [comment]
It's best to let Github close the issue when the PR is merged.

**Comment by jaydenseric** [comment]
Published in [jsdoc-md@1.7.0](https://github.com/jaydenseric/jsdoc-md/releases/tag/v1.7.0) 🚀
